# Generated by Django 5.1.4 on 2025-02-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_coursefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='file',
        ),
    ]
