# Generated by Django 5.1.4 on 2025-05-01 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_curriculum_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.curriculum'),
        ),
    ]
