# Generated by Django 5.1.4 on 2025-05-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_group_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course_year',
        ),
        migrations.AddField(
            model_name='group',
            name='course_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
