# Generated by Django 5.1.4 on 2025-05-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_user_course_year_group_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
