# Generated by Django 5.1.4 on 2025-05-02 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_user_course_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDisciplineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.curriculumitem')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'curriculum_item')},
            },
        ),
    ]
