# Generated by Django 5.1.4 on 2025-05-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_groupdisciplineassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdisciplineassignment',
            name='lab_works_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
