# Generated by Django 5.1.4 on 2025-05-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_studentwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdisciplineassignment',
            name='lab_works_count',
        ),
        migrations.AddField(
            model_name='groupdisciplineassignment',
            name='lab_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество лабораторных работ'),
        ),
    ]
