# Generated by Django 5.1.4 on 2025-05-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_curriculumitem_has_practice_alter_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdisciplineassignment',
            name='practice_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
