# Generated by Django 5.1.4 on 2025-05-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_groupdisciplineassignment_practice_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdisciplineassignment',
            name='practice_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
