# Generated by Django 5.1.4 on 2025-05-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_groupdisciplineassignment_practice_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentwork',
            name='work_type',
            field=models.CharField(choices=[('lab', 'Лабораторная'), ('practice', 'Практика'), ('coursework', 'Курсовая работа'), ('courseproject', 'Курсовой проект'), ('referat', 'Реферат'), ('rgr', 'РГР'), ('exam', 'Экзамен'), ('zachet', 'Зачет'), ('zachet_grade', 'Зачет с оценкой')], max_length=50),
        ),
    ]
